CREATE TABLE qr_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    folder_id UUID,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('website',
    'pdf',
    'images',
    'video',
    'wifi',
    'menu',
    'business',
    'vcard',
    'mp3',
    'apps',
    'links',
    'coupon',
    'facebook',
    'instagram',
    'social',
    'whatsapp')),
    content JSONB NOT NULL,
    qr_image_url TEXT,
    customization JSONB DEFAULT '{}'::jsonb,
    is_dynamic BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    scan_count INTEGER DEFAULT 0,
    unique_scan_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);